-- Show non-default users
SELECT username 
from all_users 
WHERE username NOT IN ('SYS','AUDSYS','SYSTEM','SYSBACKUP','SYSDG','SYSKM','SYSRAC','OUTLN','XS$NULL','GSMADMIN_INTERNAL','GSMUSER',
    'DIP','REMOTE_SCHEDULER_AGENT','DBSFWUSER','DGPDB_INT','ORACLE_OCM','SYS$UMF','DBSNMP','APPQOSSYS','GSMCATUSER','GGSYS','XDB','ANONYMOUS','WMSYS',
    'DVSYS','OJVMSYS','CTXSYS','ORDSYS','ORDDATA','ORDPLUGINS','SI_INFORMTN_SCHEMA','MDSYS','OLAPSYS','MDDATA','LBACSYS','DVF','HR',
    'APEX_PUBLIC_USER','APEX_190100','APEX_220100','FLOWS_FILES','APEX_INSTANCE_ADMIN_USER','APEX_LISTENER','APEX_REST_PUBLIC_USER','ORDS_PUBLIC_USER','ORDS_METADATA');
