
SET DEFINE OFF;

INSERT INTO geo_languages (code, language_name_en) VALUES ('af','Afrikaans');
INSERT INTO geo_languages (code, language_name_en) VALUES ('af-ZA','Afrikaans (South Africa)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar','Arabic');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-AE','Arabic (U.A.E.)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-BH','Arabic (Bahrain)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-DZ','Arabic (Algeria)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-EG','Arabic (Egypt)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-IQ','Arabic (Iraq)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-JO','Arabic (Jordan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-KW','Arabic (Kuwait)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-LB','Arabic (Lebanon)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-LY','Arabic (Libya)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-MA','Arabic (Morocco)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-OM','Arabic (Oman)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-QA','Arabic (Qatar)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-SA','Arabic (Saudi Arabia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-SY','Arabic (Syria)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-TN','Arabic (Tunisia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ar-YE','Arabic (Yemen)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('az','Azeri (Latin)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('az-AZ','Azeri (Latin,Cyrillic) (Azerbaijan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('be','Belarusian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('be-BY','Belarusian (Belarus)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('bg','Bulgarian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('bg-BG','Bulgarian (Bulgaria)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('bs','Bosnian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('bs-BA','Bosnian (Bosnia and Herzegovina)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ca','Catalan');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ca-ES','Catalan (Spain)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('cs','Czech');
INSERT INTO geo_languages (code, language_name_en) VALUES ('cs-CZ','Czech (Czech Republic)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('cy','Welsh');
INSERT INTO geo_languages (code, language_name_en) VALUES ('cy-GB','Welsh (United Kingdom)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('da','Danish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('da-DK','Danish (Denmark)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de','German');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de-AT','German (Austria)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de-CH','German (Switzerland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de-DE','German (Germany)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de-LI','German (Liechtenstein)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('de-LU','German (Luxembourg)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('dv','Divehi');
INSERT INTO geo_languages (code, language_name_en) VALUES ('dv-MV','Divehi (Maldives)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('el','Greek');
INSERT INTO geo_languages (code, language_name_en) VALUES ('el-GR','Greek (Greece)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en','English');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-AU','English (Australia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-BZ','English (Belize)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-CA','English (Canada)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-CB','English (Caribbean)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-GB','English (United Kingdom)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-IE','English (Ireland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-JM','English (Jamaica)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-NZ','English (New Zealand)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-PH','English (Republic of the Philippines)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-TT','English (Trinidad and Tobago)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-US','English (United States)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-ZA','English (South Africa)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('en-ZW','English (Zimbabwe)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('eo','Esperanto');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es','Spanish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-AR','Spanish (Argentina)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-BO','Spanish (Bolivia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-CL','Spanish (Chile)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-CO','Spanish (Colombia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-CR','Spanish (Costa Rica)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-DO','Spanish (Dominican Republic)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-EC','Spanish (Ecuador)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-ES','Spanish (Spain,Castilian)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-GT','Spanish (Guatemala)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-HN','Spanish (Honduras)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-MX','Spanish (Mexico)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-NI','Spanish (Nicaragua)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-PA','Spanish (Panama)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-PE','Spanish (Peru)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-PR','Spanish (Puerto Rico)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-PY','Spanish (Paraguay)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-SV','Spanish (El Salvador)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-UY','Spanish (Uruguay)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('es-VE','Spanish (Venezuela)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('et','Estonian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('et-EE','Estonian (Estonia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('eu','Basque');
INSERT INTO geo_languages (code, language_name_en) VALUES ('eu-ES','Basque (Spain)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fa','Farsi');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fa-IR','Farsi (Iran)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fi','Finnish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fi-FI','Finnish (Finland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fo','Faroese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fo-FO','Faroese (Faroe Islands)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr','French');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-BE','French (Belgium)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-CA','French (Canada)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-CH','French (Switzerland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-FR','French (France)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-LU','French (Luxembourg)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('fr-MC','French (Principality of Monaco)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('gl','Galician');
INSERT INTO geo_languages (code, language_name_en) VALUES ('gl-ES','Galician (Spain)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('gu','Gujarati');
INSERT INTO geo_languages (code, language_name_en) VALUES ('gu-IN','Gujarati (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('he','Hebrew');
INSERT INTO geo_languages (code, language_name_en) VALUES ('he-IL','Hebrew (Israel)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hi','Hindi');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hi-IN','Hindi (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hr','Croatian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hr-BA','Croatian (Bosnia and Herzegovina)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hr-HR','Croatian (Croatia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hu','Hungarian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hu-HU','Hungarian (Hungary)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hy','Armenian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('hy-AM','Armenian (Armenia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('id','Indonesian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('id-ID','Indonesian (Indonesia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('is','Icelandic');
INSERT INTO geo_languages (code, language_name_en) VALUES ('is-IS','Icelandic (Iceland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('it','Italian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('it-CH','Italian (Switzerland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('it-IT','Italian (Italy)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ja','Japanese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ja-JP','Japanese (Japan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ka','Georgian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ka-GE','Georgian (Georgia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kk','Kazakh');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kk-KZ','Kazakh (Kazakhstan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kn','Kannada');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kn-IN','Kannada (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ko','Korean');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ko-KR','Korean (Korea)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kok','Konkani');
INSERT INTO geo_languages (code, language_name_en) VALUES ('kok-IN','Konkani (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ky','Kyrgyz');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ky-KG','Kyrgyz (Kyrgyzstan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('lt','Lithuanian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('lt-LT','Lithuanian (Lithuania)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('lv','Latvian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('lv-LV','Latvian (Latvia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mi','Maori');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mi-NZ','Maori (New Zealand)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mk','FYRO Macedonian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mk-MK','FYRO Macedonian (Former Yugoslav Republic of Macedonia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mn','Mongolian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mn-MN','Mongolian (Mongolia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mr','Marathi');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mr-IN','Marathi (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ms','Malay');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ms-BN','Malay (Brunei Darussalam)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ms-MY','Malay (Malaysia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mt','Maltese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('mt-MT','Maltese (Malta)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nb','Norwegian (Bokm?l)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nb-NO','Norwegian (Bokm?l) (Norway)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nl','Dutch');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nl-BE','Dutch (Belgium)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nl-NL','Dutch (Netherlands)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nn','Norwegian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('nn-NO','Norwegian (Nynorsk) (Norway)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ns','Northern Sotho');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ns-ZA','Northern Sotho (South Africa)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pa','Punjabi');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pa-IN','Punjabi (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pl','Polish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pl-PL','Polish (Poland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ps','Pashto');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ps-AR','Pashto (Afghanistan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pt','Portuguese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pt-BR','Portuguese (Brazil)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('pt-PT','Portuguese (Portugal)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('qu','Quechua');
INSERT INTO geo_languages (code, language_name_en) VALUES ('qu-BO','Quechua (Bolivia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('qu-EC','Quechua (Ecuador)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('qu-PE','Quechua (Peru)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ro','Romanian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ro-RO','Romanian (Romania)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ru','Russian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ru-RU','Russian (Russia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sa','Sanskrit');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sa-IN','Sanskrit (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('se','Sami (Northern)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('se-FI','Sami (Northern,Skolt,Inari) (Finland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('se-NO','Sami (Northern,Lule,Southern) (Norway)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('se-SE','Sami (Northern,Lule,Southern) (Sweden)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sk','Slovak');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sk-SK','Slovak (Slovakia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sl','Slovenian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sl-SI','Slovenian (Slovenia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sq','Albanian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sq-AL','Albanian (Albania)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sr','Serbian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sr-BA','Serbian (Latin,Cyrillic) (Bosnia and Herzegovina)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sr-SP','Serbian (Latin,Cyrillic) (Serbia and Montenegro)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sv','Swedish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sv-FI','Swedish (Finland)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sv-SE','Swedish (Sweden)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sw','Swahili');
INSERT INTO geo_languages (code, language_name_en) VALUES ('sw-KE','Swahili (Kenya)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('syr','Syriac');
INSERT INTO geo_languages (code, language_name_en) VALUES ('syr-SY','Syriac (Syria)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ta','Tamil');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ta-IN','Tamil (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('te','Telugu');
INSERT INTO geo_languages (code, language_name_en) VALUES ('te-IN','Telugu (India)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('th','Thai');
INSERT INTO geo_languages (code, language_name_en) VALUES ('th-TH','Thai (Thailand)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tl','Tagalog');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tl-PH','Tagalog (Philippines)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tn','Tswana');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tn-ZA','Tswana (South Africa)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tr','Turkish');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tr-TR','Turkish (Turkey)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tt','Tatar');
INSERT INTO geo_languages (code, language_name_en) VALUES ('tt-RU','Tatar (Russia)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ts','Tsonga');
INSERT INTO geo_languages (code, language_name_en) VALUES ('uk','Ukrainian');
INSERT INTO geo_languages (code, language_name_en) VALUES ('uk-UA','Ukrainian (Ukraine)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ur','Urdu');
INSERT INTO geo_languages (code, language_name_en) VALUES ('ur-PK','Urdu (Islamic Republic of Pakistan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('uz','Uzbek (Latin)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('uz-UZ','Uzbek (Latin,Cyrillic) (Uzbekistan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('vi','Vietnamese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('vi-VN','Vietnamese (Viet Nam)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('xh','Xhosa');
INSERT INTO geo_languages (code, language_name_en) VALUES ('xh-ZA','Xhosa (South Africa)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh','Chinese');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh-CN','Chinese (Simplified) (PRC)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh-HK','Chinese (Traditional) (Hong Kong)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh-MO','Chinese (Traditional) (Macau)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh-SG','Chinese (Simplified) (Singapore)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zh-TW','Chinese (Traditional) (Taiwan)');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zu','Zulu');
INSERT INTO geo_languages (code, language_name_en) VALUES ('zu-ZA','Zulu (South Africa)');
COMMIT;

EXECUTE DBMS_STATS.GATHER_TABLE_STATS(ownname=>USER, tabname=>UPPER('geo_languages'), cascade=>TRUE, estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE, method_opt=>'for all columns size auto');
